// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CustomersPhones {
  _id?: string;
  customer_id?: string;
  phone: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
}
