// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthcarePhones } from "./HealthcarePhones";

export interface Healthcare {
  _id?: string;
  healthcareId?: string;
  name: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
  phones: Array<HealthcarePhones>;
}
