// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfesionalsPhones } from "./ProfesionalsPhones";

export interface Profesionals { _id?: string, profesionalId?: string, firstName: string, lastName: string, degree: string, licence: string, email: string, enabled: boolean, createdAt?: string, updatedAt?: string, phones: Array<ProfesionalsPhones>, }