// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProfesionalsByRooms {
  _id?: string;
  profesionalId: string;
  roomsId: string;
  profesionalFullName: string;
  roomsName: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
}
