// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProfesionalsPhones { _id?: string, profesional_id?: string, phone: string, enabled: boolean, createdAt?: string, updatedAt?: string, }