// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Rooms {
  _id?: string;
  roomId?: string;
  name: string;
  description: string;
  phone: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
}
